# Generated by Django 3.1.7 on 2021-06-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalDonation',
        ),
    ]
