# Generated by Django 3.1.7 on 2021-06-30 14:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donation', '0002_delete_historicaldonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDonation',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('father', models.CharField(max_length=30, verbose_name='Father Name')),
                ('village', models.CharField(max_length=20, verbose_name='Village')),
                ('mobile', models.IntegerField(verbose_name='Mobile number')),
                ('donation_type', models.CharField(choices=[('AMOUNT', 'amount'), ('OTHER', 'other')], max_length=10)),
                ('amount', models.IntegerField(default=0, verbose_name='Amount')),
                ('other', models.CharField(max_length=255, verbose_name='other')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='date_joined')),
                ('remark', models.CharField(max_length=255, verbose_name='remark')),
                ('due', models.IntegerField(default=0, verbose_name='Due')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('agent_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical donation',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
