# Generated by Django 3.1.7 on 2021-07-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_historicaldonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='d_type',
            field=models.CharField(blank=True, choices=[('CONST', 'const'), ('EVENT', 'event'), ('OTHER', 'other')], default='OTHER', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicaldonation',
            name='d_type',
            field=models.CharField(blank=True, choices=[('CONST', 'const'), ('EVENT', 'event'), ('OTHER', 'other')], default='OTHER', max_length=10, null=True),
        ),
    ]
