# Generated by Django 3.1.7 on 2021-07-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_auto_20210723_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='event_type',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Event Type'),
        ),
        migrations.AddField(
            model_name='historicaldonation',
            name='event_type',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Event Type'),
        ),
    ]
