# Generated by Django 3.1.7 on 2021-06-30 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constcontract',
            name='c_father',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contractor father'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='check_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Check number '),
        ),
        migrations.AlterField(
            model_name='expense',
            name='due',
            field=models.IntegerField(blank=True, null=True, verbose_name='Due of expense if any'),
        ),
        migrations.AlterField(
            model_name='expother',
            name='expense',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='expense.expense'),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='check_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Check number '),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='due',
            field=models.IntegerField(blank=True, null=True, verbose_name='Due of expense if any'),
        ),
    ]
