# Generated by Django 3.1.7 on 2021-07-01 16:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense', '0004_auto_20210701_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalExpense',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('biller_name', models.CharField(max_length=20, verbose_name='Name of shop')),
                ('amount', models.IntegerField(verbose_name='Amount of expense')),
                ('amount_type', models.CharField(max_length=10, verbose_name='Cash or check')),
                ('due', models.IntegerField(blank=True, null=True, verbose_name='Due of expense if any')),
                ('check_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Check number ')),
                ('remark', models.CharField(max_length=30, verbose_name='Description')),
                ('rate', models.CharField(max_length=10, verbose_name='Price per item')),
                ('exp_date', models.DateField(default=datetime.date.today, verbose_name='expense date')),
                ('quantity', models.CharField(max_length=10, verbose_name='Quantity ')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('agent_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical expense',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
