# Generated by Django 3.1.7 on 2021-07-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_historicalconstcontract_historicalconstmaterial_historicalexpother'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='exp_type',
            field=models.CharField(blank=True, default='other', max_length=10, null=True, verbose_name='Expense type '),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='exp_type',
            field=models.CharField(blank=True, default='other', max_length=10, null=True, verbose_name='Expense type '),
        ),
    ]
