# Generated by Django 3.1.7 on 2021-07-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_auto_20210723_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='exp_name',
            field=models.CharField(blank=True, default='Name', max_length=30, null=True, verbose_name='Expense Name '),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='exp_name',
            field=models.CharField(blank=True, default='Name', max_length=30, null=True, verbose_name='Expense Name '),
        ),
    ]
