# Generated by Django 3.1.7 on 2021-03-25 10:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'managament'), (2, 'commitymember'), (3, 'admin')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mobile', models.IntegerField(unique=True, verbose_name='Mobile number')),
                ('father', models.CharField(max_length=30, verbose_name='Father Name')),
                ('village', models.CharField(max_length=20, verbose_name='Village')),
                ('alt_mobile', models.IntegerField(verbose_name='Alternative Mobile number')),
                ('occupation', models.CharField(default='NA', max_length=20, verbose_name='Last Name')),
                ('address', models.CharField(default='', max_length=255, verbose_name='address')),
                ('sex', models.CharField(choices=[('1', 'male'), ('2', 'female')], max_length=5)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('roles', models.ManyToManyField(to='users.Role')),
            ],
            options={
                'db_table': 'core_user',
            },
        ),
    ]
