# Generated by Django 3.1.7 on 2021-03-25 11:22

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210325_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='alt_mobile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='father',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='user',
            name='village',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(default='', max_length=255, verbose_name='Last Name')),
                ('father', models.CharField(max_length=30, verbose_name='Father Name')),
                ('village', models.CharField(max_length=20, verbose_name='Village')),
                ('alt_mobile', models.IntegerField(verbose_name='Alternative Mobile number')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(default='NA', max_length=20, verbose_name='Last Name')),
                ('address', models.CharField(default='', max_length=255, verbose_name='address')),
                ('date_joined', models.DateField(default=datetime.date.today, verbose_name='date_joined')),
                ('gender', models.CharField(choices=[('1', 'male'), ('2', 'female')], max_length=5)),
                ('roles', models.ManyToManyField(to='users.Role')),
            ],
            options={
                'db_table': 'core_profile',
            },
        ),
    ]
