# Generated by Django 3.1.7 on 2021-03-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210325_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='roles',
        ),
        migrations.AddField(
            model_name='user',
            name='is_commitymember',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_managmentuser',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
